name: Package and Publish Helm Chart

on:
  push:
    branches:
      - master  # Cambia esto al nombre de tu rama principal

jobs:
  release:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Publish Helm Chart
      uses:  helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: ${{ secrets.TOKEN }}
